name: Build caddy-cloudflare

on:
  workflow_dispatch: # allows manual running
  schedule:
    - cron: 0 0 * * *
  push:
    branches: main
    paths:
      - Dockerfile

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Login to GitHub Container Repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and publish container image
        uses: docker/build-push-action@v6
        id: push
        with:
          context: .
          file: Dockerfile
          push: true
          tags: neudoerf/caddy-cloudflare:latest
